### ISSUE TITLE
Add register/sign-in/sign-out buttons to top navigation

### ISSUE THREAD

**Issue by jaydorsey** [duaimei/tech_for_justice#32]
This is a convenience for previously registered users.

Currently, there is no contextual (based on whether you're logged in or not) sign-in/register or sign-out button on the application. Would suggest adding one for easy access (particularly the sign-out one)

Currently the sign out only shows up on certain pages after you're logged in and it isn't easy to get to.

![image](https://cloud.githubusercontent.com/assets/191564/16367154/a347f2ec-3bee-11e6-9a15-7729f89439b5.png)

Desired behavior: 

- Sign In or Register link available when not signed in, in upper right of application layout
- Sign Out link available when signed in, in upper right of application layout

**Comment by duaimei** [comment]
This issue has been remedied in the following ways:

1) The user is redirected to the splash page when not signed in, which has easy access to the registration page.

2) The logout button is one the upper navigation bar and available in every page of the application.
