### ISSUE TITLE
Replace Document New video

### ISSUE THREAD

**Issue by duaimei** [duaimei/tech_for_justice#66]
Add a video to the edit view, replace video on the new view. Follow the styling on documents/new.

https://www.youtube.com/watch?v=3D-GO0qzU_o&index=1&list=PLIoHkUByRQSbW3gHYYl9qe9YxOYybPxeB

**Comment by carolynjan17** [comment]
Think I took care of this one to.

**Comment by duaimei** [comment]
This has been changed, but the permissions on the video need to be changed for it to show up.

**Comment by duaimei** [comment]
When going through the New and Update documents sections videos are available in the following sections:
User Information, User Case Information, Reasons for Expungement, and User References.

This issue is closed.
