### ISSUE TITLE
Add Video to the User Case Information View

### ISSUE THREAD

**Issue by duaimei** [duaimei/tech_for_justice#67]
Add a video to the user case information new and edit view, follow the styling on documents/new.

https://www.youtube.com/watch?v=3D-GO0qzU_o&index=1&list=PLIoHkUByRQSbW3gHYYl9qe9YxOYybPxeB

**Comment by duaimei** [comment]
So this is pretty straightforward to do, following the example of the documents/new view: https://github.com/duaimei/tech_for_justice/blob/master/app/views/documents/new.html.erb

Basically all you need to do is add this to the top of the view (making sure that this view is using the form_layout)

<% @video_url = "https://www.youtube.com/embed/2EfHtzauHcM" %>

(But obviously with the right embed url of the video)

**Comment by carolynjan17** [comment]
Added on carolyn_c9
