### ISSUE TITLE
UI User Case Information changes

### ISSUE THREAD

**Issue by duaimei** [duaimei/tech_for_justice#73]
IN PROGRESS:
Case end date -> add a date picking calendar + text box. Should be able to just do the month/day/year. 

From Carolyn: added button to move to user arguments and date picker button to form.html. I didn't have exact names for things so I used a generic name. I'll submit a pull request.

COMPLETED:

The following fields should be dropdowns:
case conclusion -> no papered, dismissed or nolle prosequi, or guilty
charge type -> (a) Its been two years since I was charged with an eligible misdemeanor but not convicted.. 
(b) its  has been 5 years I was charged but not convicted with an ineligible misdemeanor...
(c) It has been 10 years since I finished parole, probation, prison, or supervised release after being charged with an eligible misdemeanor or eligible fleony convictionEligible felony or inlegibile 

The "is case pending" question should have a yes/no radio button.

Add button to move onto User Arguments

**Comment by duaimei** [comment]
I added a section and logic so that the records that are associated with the document are listed at the top. making that pretty still needs to happen.

**Comment by duaimei** [comment]
I have assigned this to carolyn.
drop down:
http://www.w3schools.com/tags/tag_select.asp
radio button:
http://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio

**Comment by carolynjan17** [comment]
Took care of the drop-down fields and the radio button for case pending. Will work on the user reference button and calendar tomorrow.

**Comment by carolynjan17** [comment]
P.S. will submit a pull request for what I have.

**Comment by duaimei** [comment]
I have accepted the PR from a couple of days ago. I was able to use Jay's comments to integrate what Carolyn did with the rails form.
